"""
#######################################################################

CCPN Data Model version 2.0.b2

Autogenerated by PyXmlMapWrite revision 1.24.2.3 on Mon Apr  6 17:00:36 2009
  from data model element ccp.general.DbRef revision 1.34.2.9

#######################################################################
======================COPYRIGHT/LICENSE START==========================

DbRef.py: python XML-I/O-mapping for CCPN data model, MetaPackage ccp.general.DbRef

Copyright (C) 2007  (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
 
A copy of this license can be found in ../../../../license/LGPL.license
 
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
 
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""
from memops.general.Constants import baseDataTypeModule as basicDataTypes
# 
#  Current package api
import ccp.api.general.DbRef

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package DBR, adding it to globalMap
  """
  
  from memops.xml.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('DBR').get('abstractTypes')
  exolinks = globalMap.get('DBR').get('exolinks')

  # Class Database
  currentMap = {}
  abstractTypes['Database'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00021'] = currentMap
  loadMaps['DBR.Database'] = currentMap
  currentMap['tag'] = 'DBR.Database'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00021'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'databases'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccp.api.general.DbRef.Database
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Database.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Database.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_ModelAdapt_2009-04-06-16:59:25_00039')

  # Attribute Database.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00046'] = currentMap
  loadMaps['DBR.Database.details'] = currentMap
  currentMap['tag'] = 'DBR.Database.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00046'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute Database.fullName
  currentMap = {}
  contentMap['fullName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00044'] = currentMap
  loadMaps['DBR.Database.fullName'] = currentMap
  currentMap['tag'] = 'DBR.Database.fullName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00044'
  currentMap['name'] = 'fullName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute Database.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute Database.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_ModelAdapt_2009-04-06-16:59:25_00041')

  # Attribute Database.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_ModelAdapt_2009-04-06-16:59:25_00044')

  # Attribute Database.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00043'] = currentMap
  loadMaps['DBR.Database.name'] = currentMap
  currentMap['tag'] = 'DBR.Database.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00043'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Database.url
  currentMap = {}
  contentMap['url'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00045'] = currentMap
  loadMaps['DBR.Database.url'] = currentMap
  currentMap['tag'] = 'DBR.Database.url'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00045'
  currentMap['name'] = 'url'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Role Database.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Database.entries
  currentMap = {}
  contentMap['entries'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00036'] = currentMap
  loadMaps['DBR.Database.entries'] = currentMap
  currentMap['tag'] = 'DBR.Database.entries'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00036'
  currentMap['name'] = 'entries'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('DBR').get('abstractTypes')
  # End of Database

  currentMap = abstractTypes.get('Database')
  aList = ['createdBy', 'guid', 'isModifiable', 'lastUnlockedBy']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'fullName', 'name', 'url']
  currentMap['simpleAttrs'] = aList
  aList = ['entries', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['entries']
  currentMap['children'] = aList

  # Class Entry
  currentMap = {}
  abstractTypes['Entry'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00020'] = currentMap
  loadMaps['DBR.Entry'] = currentMap
  currentMap['tag'] = 'DBR.Entry'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00020'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'entries'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccp.api.general.DbRef.Entry
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Entry.altCode
  currentMap = {}
  contentMap['altCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00004'] = currentMap
  loadMaps['DBR.Entry.altCode'] = currentMap
  currentMap['tag'] = 'DBR.Entry.altCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00004'
  currentMap['name'] = 'altCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Entry.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Entry.code
  currentMap = {}
  contentMap['code'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00040'] = currentMap
  loadMaps['DBR.Entry.code'] = currentMap
  currentMap['tag'] = 'DBR.Entry.code'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00040'
  currentMap['name'] = 'code'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Entry.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00042'] = currentMap
  loadMaps['DBR.Entry.details'] = currentMap
  currentMap['tag'] = 'DBR.Entry.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00042'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute Entry.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00005'] = currentMap
  loadMaps['DBR.Entry.name'] = currentMap
  currentMap['tag'] = 'DBR.Entry.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00005'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Entry.release
  currentMap = {}
  contentMap['release'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00039'] = currentMap
  loadMaps['DBR.Entry.release'] = currentMap
  currentMap['tag'] = 'DBR.Entry.release'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00039'
  currentMap['name'] = 'release'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Entry.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00038'] = currentMap
  loadMaps['DBR.Entry.serial'] = currentMap
  currentMap['tag'] = 'DBR.Entry.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00038'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute Entry.subCode
  currentMap = {}
  contentMap['subCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00003'] = currentMap
  loadMaps['DBR.Entry.subCode'] = currentMap
  currentMap['tag'] = 'DBR.Entry.subCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00003'
  currentMap['name'] = 'subCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Entry.url
  currentMap = {}
  contentMap['url'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00041'] = currentMap
  loadMaps['DBR.Entry.url'] = currentMap
  currentMap['tag'] = 'DBR.Entry.url'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:30_00041'
  currentMap['name'] = 'url'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Role Entry.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of Entry

  currentMap = abstractTypes.get('Entry')
  aList = ['altCode', 'code', 'name', 'serial', 'subCode']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'release', 'url']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Out-of-package link to Database
  currentMap = {}
  exolinks['Database'] = currentMap
  loadMaps['DBR.exo-Database'] = currentMap
  currentMap['tag'] = 'DBR.exo-Database'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00021'
  currentMap['name'] = 'Database'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccp.api.general.DbRef.Database
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))

  # Out-of-package link to Entry
  currentMap = {}
  exolinks['Entry'] = currentMap
  loadMaps['DBR.exo-Entry'] = currentMap
  currentMap['tag'] = 'DBR.exo-Entry'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00020'
  currentMap['name'] = 'Entry'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccp.api.general.DbRef.Entry
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
