"""
#######################################################################

CCPN Data Model version 2.0.b2

Autogenerated by PyXmlMapWrite revision 1.24.2.3 on Mon Apr  6 17:00:36 2009
  from data model element ccp.general.Taxonomy revision 1.36.2.9

#######################################################################
======================COPYRIGHT/LICENSE START==========================

Taxonomy.py: python XML-I/O-mapping for CCPN data model, MetaPackage ccp.general.Taxonomy

Copyright (C) 2007 Anne Pajon (MSD group, EBI)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
 
A copy of this license can be found in ../../../../license/LGPL.license
 
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
 
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- PIMS website (http://www.pims-lims.org)

- email: Anne Pajon, pajon@ebi.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
A. Pajon, J. Ionides, J. Diprose, J. Fillon, R. Fogh, A.W. Ashton,
H. Berman, W. Boucher, M. Cygler, E. Deleury, R. Esnouf, J. Janin, R. Kim,
I. Krimm, C.L. Lawson, E. Oeuillet, A. Poupon, S. Raymond, T. Stevens,
H. van Tilbeurgh, J. Westbrook, P. Wood, E. Ulrich, W. Vranken, L. Xueli,
E. Laue, D.I. Stuart, and K. Henrick (2005). Design of a Data Model for
Developing Laboratory Information Management and Analysis Systems for
Protein Production. Proteins: Structure, Function and Bioinformatics 58,
278-284.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""
from memops.general.Constants import baseDataTypeModule as basicDataTypes
# 
#  Current package api
import ccp.api.general.Taxonomy

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package TAXO, adding it to globalMap
  """
  
  from memops.xml.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('TAXO').get('abstractTypes')
  exolinks = globalMap.get('TAXO').get('exolinks')

  # Class NaturalSource
  currentMap = {}
  abstractTypes['NaturalSource'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:19:50_00003'] = currentMap
  loadMaps['TAXO.NaturalSource'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:19:50_00003'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'naturalSources'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccp.api.general.Taxonomy.NaturalSource
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute NaturalSource.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute NaturalSource.atccNumber
  currentMap = {}
  contentMap['atccNumber'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00008'] = currentMap
  loadMaps['TAXO.NaturalSource.atccNumber'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.atccNumber'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00008'
  currentMap['name'] = 'atccNumber'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.cellLine
  currentMap = {}
  contentMap['cellLine'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00012'] = currentMap
  loadMaps['TAXO.NaturalSource.cellLine'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.cellLine'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00012'
  currentMap['name'] = 'cellLine'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.cellLocation
  currentMap = {}
  contentMap['cellLocation'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00013'] = currentMap
  loadMaps['TAXO.NaturalSource.cellLocation'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.cellLocation'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00013'
  currentMap['name'] = 'cellLocation'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute NaturalSource.cellType
  currentMap = {}
  contentMap['cellType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00014'] = currentMap
  loadMaps['TAXO.NaturalSource.cellType'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.cellType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00014'
  currentMap['name'] = 'cellType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00024'] = currentMap
  loadMaps['TAXO.NaturalSource.details'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00024'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute NaturalSource.fraction
  currentMap = {}
  contentMap['fraction'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00011'] = currentMap
  loadMaps['TAXO.NaturalSource.fraction'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.fraction'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00011'
  currentMap['name'] = 'fraction'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.geneMnemonic
  currentMap = {}
  contentMap['geneMnemonic'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00015'] = currentMap
  loadMaps['TAXO.NaturalSource.geneMnemonic'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.geneMnemonic'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00015'
  currentMap['name'] = 'geneMnemonic'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.genus
  currentMap = {}
  contentMap['genus'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00005'] = currentMap
  loadMaps['TAXO.NaturalSource.genus'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.genus'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00005'
  currentMap['name'] = 'genus'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.ictvCode
  currentMap = {}
  contentMap['ictvCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00009'] = currentMap
  loadMaps['TAXO.NaturalSource.ictvCode'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.ictvCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00009'
  currentMap['name'] = 'ictvCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.ncbiTaxonomyId
  currentMap = {}
  contentMap['ncbiTaxonomyId'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00003'] = currentMap
  loadMaps['TAXO.NaturalSource.ncbiTaxonomyId'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.ncbiTaxonomyId'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00003'
  currentMap['name'] = 'ncbiTaxonomyId'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.organ
  currentMap = {}
  contentMap['organ'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00016'] = currentMap
  loadMaps['TAXO.NaturalSource.organ'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.organ'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00016'
  currentMap['name'] = 'organ'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.organelle
  currentMap = {}
  contentMap['organelle'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00017'] = currentMap
  loadMaps['TAXO.NaturalSource.organelle'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.organelle'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00017'
  currentMap['name'] = 'organelle'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.organismAcronym
  currentMap = {}
  contentMap['organismAcronym'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00007'] = currentMap
  loadMaps['TAXO.NaturalSource.organismAcronym'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.organismAcronym'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00007'
  currentMap['name'] = 'organismAcronym'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.organismName
  currentMap = {}
  contentMap['organismName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00002'] = currentMap
  loadMaps['TAXO.NaturalSource.organismName'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.organismName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00002'
  currentMap['name'] = 'organismName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.plasmid
  currentMap = {}
  contentMap['plasmid'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00021'] = currentMap
  loadMaps['TAXO.NaturalSource.plasmid'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.plasmid'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00021'
  currentMap['name'] = 'plasmid'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.plasmidDetails
  currentMap = {}
  contentMap['plasmidDetails'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00022'] = currentMap
  loadMaps['TAXO.NaturalSource.plasmidDetails'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.plasmidDetails'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00022'
  currentMap['name'] = 'plasmidDetails'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute NaturalSource.scientificName
  currentMap = {}
  contentMap['scientificName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00004'] = currentMap
  loadMaps['TAXO.NaturalSource.scientificName'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.scientificName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00004'
  currentMap['name'] = 'scientificName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.secretion
  currentMap = {}
  contentMap['secretion'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00023'] = currentMap
  loadMaps['TAXO.NaturalSource.secretion'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.secretion'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00023'
  currentMap['name'] = 'secretion'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute NaturalSource.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00001'] = currentMap
  loadMaps['TAXO.NaturalSource.serial'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00001'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute NaturalSource.species
  currentMap = {}
  contentMap['species'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00006'] = currentMap
  loadMaps['TAXO.NaturalSource.species'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.species'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00006'
  currentMap['name'] = 'species'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.strain
  currentMap = {}
  contentMap['strain'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00010'] = currentMap
  loadMaps['TAXO.NaturalSource.strain'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.strain'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00010'
  currentMap['name'] = 'strain'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.subVariant
  currentMap = {}
  contentMap['subVariant'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00020'] = currentMap
  loadMaps['TAXO.NaturalSource.subVariant'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.subVariant'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00020'
  currentMap['name'] = 'subVariant'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00036')

  # Attribute NaturalSource.tissue
  currentMap = {}
  contentMap['tissue'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00018'] = currentMap
  loadMaps['TAXO.NaturalSource.tissue'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.tissue'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00018'
  currentMap['name'] = 'tissue'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute NaturalSource.variant
  currentMap = {}
  contentMap['variant'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00019'] = currentMap
  loadMaps['TAXO.NaturalSource.variant'] = currentMap
  currentMap['tag'] = 'TAXO.NaturalSource.variant'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:38_00019'
  currentMap['name'] = 'variant'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role NaturalSource.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')
  # End of NaturalSource

  currentMap = abstractTypes.get('NaturalSource')
  aList = ['serial']
  currentMap['headerAttrs'] = aList
  aList = ['atccNumber', 'cellLine', 'cellLocation', 'cellType', 'details', 'fraction', 'geneMnemonic', 'genus', 'ictvCode', 'ncbiTaxonomyId', 'organ', 'organelle', 'organismAcronym', 'organismName', 'plasmid', 'plasmidDetails', 'scientificName', 'secretion', 'species', 'strain', 'subVariant', 'tissue', 'variant']
  currentMap['simpleAttrs'] = aList
  aList = ['access', 'applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Taxonomy
  currentMap = {}
  abstractTypes['Taxonomy'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-09-05-12:55:15_00002'] = currentMap
  loadMaps['TAXO.Taxonomy'] = currentMap
  currentMap['tag'] = 'TAXO.Taxonomy'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:55:15_00002'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'taxonomies'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccp.api.general.Taxonomy.Taxonomy
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Taxonomy.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Taxonomy.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_ModelAdapt_2009-04-06-16:59:25_00039')

  # Attribute Taxonomy.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute Taxonomy.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_ModelAdapt_2009-04-06-16:59:25_00041')

  # Attribute Taxonomy.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_ModelAdapt_2009-04-06-16:59:25_00044')

  # Attribute Taxonomy.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-09-05-12:55:44_00007'] = currentMap
  loadMaps['TAXO.Taxonomy.name'] = currentMap
  currentMap['tag'] = 'TAXO.Taxonomy.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:55:44_00007'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role Taxonomy.access
  contentMap['access'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:03:01_00014')

  # Role Taxonomy.naturalSources
  currentMap = {}
  contentMap['naturalSources'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-09-05-12:55:44_00006'] = currentMap
  loadMaps['TAXO.Taxonomy.naturalSources'] = currentMap
  currentMap['tag'] = 'TAXO.Taxonomy.naturalSources'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:55:44_00006'
  currentMap['name'] = 'naturalSources'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('TAXO').get('abstractTypes')
  # End of Taxonomy

  currentMap = abstractTypes.get('Taxonomy')
  aList = ['createdBy', 'guid', 'isModifiable', 'lastUnlockedBy']
  currentMap['headerAttrs'] = aList
  aList = ['name']
  currentMap['simpleAttrs'] = aList
  aList = ['naturalSources', 'access', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['naturalSources']
  currentMap['children'] = aList

  # Out-of-package link to NaturalSource
  currentMap = {}
  exolinks['NaturalSource'] = currentMap
  loadMaps['TAXO.exo-NaturalSource'] = currentMap
  currentMap['tag'] = 'TAXO.exo-NaturalSource'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:19:50_00003'
  currentMap['name'] = 'NaturalSource'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccp.api.general.Taxonomy.NaturalSource
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to Taxonomy
  currentMap = {}
  exolinks['Taxonomy'] = currentMap
  loadMaps['TAXO.exo-Taxonomy'] = currentMap
  currentMap['tag'] = 'TAXO.exo-Taxonomy'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:55:15_00002'
  currentMap['name'] = 'Taxonomy'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccp.api.general.Taxonomy.Taxonomy
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
