all: library examples

library: shared Implementation AccessControl KeywordDefinition Affiliation AnnealProtocol DataLocation ChemElement Stereochemistry DbRef Taxonomy Template Classification Location Citation NmrExpPrototype ChemComp Holder Instrument ChemCompLabel ChemCompCharge AnalysisProfile NmrReference ChemCompCoord Method Molecule NameMapping LabeledMolecule MolSystem RefSampleComponent Validation Symmetry Sample Target MolStructure Crystallization Protocol ExpBlueprint Nmr Experiment NmrConstraint NmrEntry Analysis Annotation NmrSim Dangle NmrCalc

clean: shared_clean Implementation_clean AccessControl_clean KeywordDefinition_clean Affiliation_clean AnnealProtocol_clean DataLocation_clean ChemElement_clean Stereochemistry_clean DbRef_clean Taxonomy_clean Template_clean Classification_clean Location_clean Citation_clean NmrExpPrototype_clean ChemComp_clean Holder_clean Instrument_clean ChemCompLabel_clean ChemCompCharge_clean AnalysisProfile_clean NmrReference_clean ChemCompCoord_clean Method_clean Molecule_clean NameMapping_clean LabeledMolecule_clean MolSystem_clean RefSampleComponent_clean Validation_clean Symmetry_clean Sample_clean Target_clean MolStructure_clean Crystallization_clean Protocol_clean ExpBlueprint_clean Nmr_clean Experiment_clean NmrConstraint_clean NmrEntry_clean Analysis_clean Annotation_clean NmrSim_clean Dangle_clean NmrCalc_clean

shared:
	make -f makeSharedCode.mk library

examples:
	make -f makeSharedCode.mk examples

Implementation:
	cd memops/api/Implementation; make

AccessControl:
	cd memops/api/AccessControl; make

KeywordDefinition:
	cd ccp/api/general/KeywordDefinition; make

Affiliation:
	cd ccp/api/general/Affiliation; make

AnnealProtocol:
	cd molsim/api/AnnealProtocol; make

DataLocation:
	cd ccp/api/general/DataLocation; make

ChemElement:
	cd ccp/api/molecule/ChemElement; make

Stereochemistry:
	cd ccp/api/molecule/Stereochemistry; make

DbRef:
	cd ccp/api/general/DbRef; make

Taxonomy:
	cd ccp/api/general/Taxonomy; make

Template:
	cd ccp/api/general/Template; make

Classification:
	cd ccp/api/lims/Classification; make

Location:
	cd ccp/api/lims/Location; make

Citation:
	cd ccp/api/general/Citation; make

NmrExpPrototype:
	cd ccp/api/nmr/NmrExpPrototype; make

ChemComp:
	cd ccp/api/molecule/ChemComp; make

Holder:
	cd ccp/api/lims/Holder; make

Instrument:
	cd ccp/api/general/Instrument; make

ChemCompLabel:
	cd ccp/api/molecule/ChemCompLabel; make

ChemCompCharge:
	cd ccp/api/molecule/ChemCompCharge; make

AnalysisProfile:
	cd ccpnmr/api/AnalysisProfile; make

NmrReference:
	cd ccp/api/nmr/NmrReference; make

ChemCompCoord:
	cd ccp/api/molecule/ChemCompCoord; make

Method:
	cd ccp/api/general/Method; make

Molecule:
	cd ccp/api/molecule/Molecule; make

NameMapping:
	cd ccpnmr/api/NameMapping; make

LabeledMolecule:
	cd ccp/api/molecule/LabeledMolecule; make

MolSystem:
	cd ccp/api/molecule/MolSystem; make

RefSampleComponent:
	cd ccp/api/lims/RefSampleComponent; make

Validation:
	cd ccp/api/molecule/Validation; make

Symmetry:
	cd molsim/api/Symmetry; make

Sample:
	cd ccp/api/lims/Sample; make

Target:
	cd ccp/api/lims/Target; make

MolStructure:
	cd ccp/api/molecule/MolStructure; make

Crystallization:
	cd ccp/api/lims/Crystallization; make

Protocol:
	cd ccp/api/lims/Protocol; make

ExpBlueprint:
	cd ccp/api/lims/ExpBlueprint; make

Nmr:
	cd ccp/api/nmr/Nmr; make

Experiment:
	cd ccp/api/lims/Experiment; make

NmrConstraint:
	cd ccp/api/nmr/NmrConstraint; make

NmrEntry:
	cd ccp/api/nmr/NmrEntry; make

Analysis:
	cd ccpnmr/api/Analysis; make

Annotation:
	cd ccp/api/general/Annotation; make

NmrSim:
	cd molsim/api/NmrSim; make

Dangle:
	cd cambridge/api/Dangle; make

NmrCalc:
	cd ccp/api/nmr/NmrCalc; make

shared_clean:
	make -f makeSharedCode.mk clean

examples_clean:
	make -f makeSharedCode.mk examples_clean

examples_realclean:
	make -f makeSharedCode.mk examples_realclean

Implementation_clean:
	cd memops/api/Implementation; make clean

AccessControl_clean:
	cd memops/api/AccessControl; make clean

KeywordDefinition_clean:
	cd ccp/api/general/KeywordDefinition; make clean

Affiliation_clean:
	cd ccp/api/general/Affiliation; make clean

AnnealProtocol_clean:
	cd molsim/api/AnnealProtocol; make clean

DataLocation_clean:
	cd ccp/api/general/DataLocation; make clean

ChemElement_clean:
	cd ccp/api/molecule/ChemElement; make clean

Stereochemistry_clean:
	cd ccp/api/molecule/Stereochemistry; make clean

DbRef_clean:
	cd ccp/api/general/DbRef; make clean

Taxonomy_clean:
	cd ccp/api/general/Taxonomy; make clean

Template_clean:
	cd ccp/api/general/Template; make clean

Classification_clean:
	cd ccp/api/lims/Classification; make clean

Location_clean:
	cd ccp/api/lims/Location; make clean

Citation_clean:
	cd ccp/api/general/Citation; make clean

NmrExpPrototype_clean:
	cd ccp/api/nmr/NmrExpPrototype; make clean

ChemComp_clean:
	cd ccp/api/molecule/ChemComp; make clean

Holder_clean:
	cd ccp/api/lims/Holder; make clean

Instrument_clean:
	cd ccp/api/general/Instrument; make clean

ChemCompLabel_clean:
	cd ccp/api/molecule/ChemCompLabel; make clean

ChemCompCharge_clean:
	cd ccp/api/molecule/ChemCompCharge; make clean

AnalysisProfile_clean:
	cd ccpnmr/api/AnalysisProfile; make clean

NmrReference_clean:
	cd ccp/api/nmr/NmrReference; make clean

ChemCompCoord_clean:
	cd ccp/api/molecule/ChemCompCoord; make clean

Method_clean:
	cd ccp/api/general/Method; make clean

Molecule_clean:
	cd ccp/api/molecule/Molecule; make clean

NameMapping_clean:
	cd ccpnmr/api/NameMapping; make clean

LabeledMolecule_clean:
	cd ccp/api/molecule/LabeledMolecule; make clean

MolSystem_clean:
	cd ccp/api/molecule/MolSystem; make clean

RefSampleComponent_clean:
	cd ccp/api/lims/RefSampleComponent; make clean

Validation_clean:
	cd ccp/api/molecule/Validation; make clean

Symmetry_clean:
	cd molsim/api/Symmetry; make clean

Sample_clean:
	cd ccp/api/lims/Sample; make clean

Target_clean:
	cd ccp/api/lims/Target; make clean

MolStructure_clean:
	cd ccp/api/molecule/MolStructure; make clean

Crystallization_clean:
	cd ccp/api/lims/Crystallization; make clean

Protocol_clean:
	cd ccp/api/lims/Protocol; make clean

ExpBlueprint_clean:
	cd ccp/api/lims/ExpBlueprint; make clean

Nmr_clean:
	cd ccp/api/nmr/Nmr; make clean

Experiment_clean:
	cd ccp/api/lims/Experiment; make clean

NmrConstraint_clean:
	cd ccp/api/nmr/NmrConstraint; make clean

NmrEntry_clean:
	cd ccp/api/nmr/NmrEntry; make clean

Analysis_clean:
	cd ccpnmr/api/Analysis; make clean

Annotation_clean:
	cd ccp/api/general/Annotation; make clean

NmrSim_clean:
	cd molsim/api/NmrSim; make clean

Dangle_clean:
	cd cambridge/api/Dangle; make clean

NmrCalc_clean:
	cd ccp/api/nmr/NmrCalc; make clean
